# Dependabot Configuration for Package Updates
# See: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: pip
    target-branch: main
    directory: /
    schedule:
      interval: daily
    labels:
      - python
      - dependabot
    open-pull-requests-limit: 3
